### ISSUE TITLE
Request: Can there be commandline flags for config options?

### ISSUE THREAD

**Issue by Leopere** [OdyseeTeam/chainquery#54]
The config is wonderful and I can modify it with sed/grep/awk etc. However, it would be absolutely lovely if you could set config variables when you invoke the main Chainquery binary. 

For example the `lbrycrdd` invocation can be set with some bash magic looking a bit like this.
```
lbrycrdd \
  -conf=${CONF_PATH:-/etc/lbrycrdd/lbrycrdd.conf} \
  -data=${DATA_DIR:-/data/} \
  -port=${PORT:-9246} \
  -pid=${PID_FILE:/var/run/lbrycrdd.pid} \
  -printtoconsole \
  -rpcport=${RPC_PORT:-9245} \
  -rpcpassword=${RPC_PASSWORD:-changeme} \
  -rpcallowip=${RPC_ALLOW_IP:-10.10.0.2} \
  -rpcuser=${RPC_USER:-lbryrpc}
```

This is helpful when you're trying to launch with environment variables in place of using a config.  This is the main supported method for passing configuration options to Dockerized processes.  It's not necessary but it would be good for reasons other than my own mainly consistency of Lbry  appliances.

**Comment by tiger5226** [comment]
It was an intentional design decision to use the config over flags/environment variables. One of the big reasons was to be able to modify them live. The config is a watched file. 

Not all of the settings are watchable yet, but will be in the end. 

With all that said we could certainly add the flags.
